added tesCheckContactUs and refactor old test
DudeAlex/AlexLeoSeleniumTests pull request #94
Opened 2023-04-14 22:00 UTC by morozanna503

2023-04-14 22:35 UTC, Timberhut commented on src/test/java/AnnaMorozTest.java
> +    public void testCheckContactUs() throws InterruptedException {
throws InterruptedException бы убрать еще! он уже не нужен

2023-04-14 22:35 UTC, Timberhut commented on src/test/java/AnnaMorozTest.java
>      public void testOpenShop() throws InterruptedException {
throws InterruptedException бы убрать!

2023-04-14 22:35 UTC, Timberhut commented on src/test/java/AnnaMorozTest.java
> +        getDriver().quit();
.quit() не нужен! Он присутствует в методе Сергея!! тест заканчивается на ассерте

2023-04-14 22:35 UTC, Timberhut commented on src/test/java/AnnaMorozTest.java
> +       getDriver().quit();
и тут тоже

2023-04-14 23:03 UTC, Timberhut commented on src/test/java/AnnaMorozTest.java
>          Thread.sleep(3000);
А без слипа не успевает сайт прогрузиться? Сергей очень их не любит, просил оставлять только в крайних случаях, если не прогружается может время хотя бы максимально сократить? сайт вроде легкий и без них все грузится! Если уберете то и throws InterruptedException бы убрать после названия метода

2023-04-14 23:45 UTC, Maria7725 requested changes
Anna, в проекте добавлен класс BaseTest и команды, которые задают Webdriver уже не нужны в каждом тесте. И driver должен вызываться через getter. Команда getDriver.quit() тоже есть в классе BaseTest и не нужна в тестах.

Также Сергей на лекции просил не ставить слипы, если они абсолютно точно не нужны. И если их добавлять, то выбирать минимально необходимое время. Проверьте пожалуйста, работает ли без них и нужно ли целых 3 секунды, если без них не обойтись.

2023-04-15 03:54 UTC, Maria7725 approved these changes

2023-04-15 04:46 UTC, merged